- name: Install nginx
  hosts: webservers
  become: true        # execute the task as root(sudo)
  remote_user: ubuntu # User used to log into the target via the connection plugin.
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx        # package name
        state: present     # if not present, install it, if present, do nothing
        update_cache: true # use apt update before installing
    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
    - name: Set to start nginx service on boot
      ansible.builtin.service:
        name: nginx
        enabled: true # set to start on boot
    - name: Write custom nginx index
      ansible.builtin.copy:
        mode: '0644'        # file permission
        src: custom/index.html   # relative file from my machine
        dest: /var/www/html/index.nginx-debian.html
